name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t fardeen2001/todo-fullstack-backend .
      - name: Publish Image to docker hub
        run: docker push fardeen2001/todo-fullstack-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull fardeen2001/todo-fullstack-backend:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_URI=$MONGO_URI fardeen2001/todo-fullstack-backend
